version: '3'
services:
  web:
    build: .
    ports: ["8080:8080"]
    links:
      - "db:database"

  db:
   # hostname: localhost
    image: postgres
    #ports:
     #- "5432:5432"
    #environment:
     # - POSTGRES_PASSWORD=docker
      #- POSTGRES_USER=docker
      #- POSTGRES_DB=message_system